# Generated by Django 4.2 on 2024-03-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simalfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='tenants',
            field=models.ManyToManyField(blank=True, to='simalfa.tenant'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='tenants',
            field=models.ManyToManyField(blank=True, to='simalfa.tenant'),
        ),
    ]
